articles/urls.py
from django.urls import path
from.import views

app_name = 'articles'
urlpatterns = [
    path('', views.articles_list, name='list'),
    path('<slug>' , views.articles_detail , name='detail'),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('Home/', views.Home),
    path('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    #in add thumbnail
    #add in author
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:100] + '...'

articles/views.py
from django.shortcuts import render , HttpResponse
from . import models

# Create your views here.
def articles_list(request):
    articles = models.Articles.objects.all().order_by('date')

    return render(request, 'articles/articleslist.html', {'articles':articles})

def articles_detail (request , slug):
    return HttpResponse(slug)

djangoBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    #return HttpResponse("Hi")
    return render(request, 'about.html')

def Home(request):
    #return HttpResponse("How are u?")
    return render(request, 'Home.html')

articles/templates/articles/articleslist.html
{%extends 'base.html'%}
{% block title %}
articles
{%endblock%}

{%block contect%}
<div class="container">
    <h1>Articles List</h1>
    {% for articles in articles %}
    <h2><a href="{% url 'articles:detail' slug=articles.slug %}">{{articles.title}}</a></h2>
    <p>{{articles.snippet}}</p>
    <p>{{articles.date}}</p>
    {% endfor %}
  </div>
  {%endblock%}

djangoBlog/templates/Home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
  <h1>Home</h1>
  <p>Welcome</p>
  </body>
</html>

djangoBlog/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
  <p>I like django</p>  
  </body>
</html>

templates/Home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Home</h1>
    <p>Welcome to my Blog</p>
  </body>
</html>

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
    <p>We love Django</p>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
  {%block title%}
Articles
  {%endblock%}
  </title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <h2><a href="{% url 'articles:list'%}">LOGO</a></h2>
    <div class="wrapper">

    {% block contect %}

    {%endblock%}

    </div>
</body>
</html>